
server:
  port: 7777
  tomcat:
    threads:
      max: 200

spring:
  kafka:
    bootstrap-servers: localhost:9092

#  task:
#    scheduling.pool.size: 20 # Количество потоков @Scheduled задач

app:
  kafka:
    topicIn: "topicIn"
    topicOut: "topicOut"
  httpbin-url: "https://httpbin.org"

resilience4j:
  rateLimiter:
    instances:
      parser:
        timeout-duration: 5s
        limit-refresh-period: 1s
        limit-for-period: 10
  bulkhead:
    instances:
      parserSemaphore:
        maxConcurrentCalls: 10
        maxWaitDuration: 5s
      parserThreadPool:
        maxThreadPoolSize: 10
        coreThreadPoolSize: 10
        queueCapacity: 10
  timelimiter:
    instances:
      parserThreadPool:
        timeoutDuration: 3s